#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("nodeIdToRowColumn() works", {

  expect_error(
    kwb.demeau:::nodeIdToRowColumn()
    # argument "nodeID" is missing, with no default
  )

})

