#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("processingData() works", {

  expect_error(
    kwb.demeau:::processingData()
    # argument "rawData" is missing, with no default
  )

})

