#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("soluteModelled() works", {

  expect_error(
    kwb.demeau:::soluteModelled()
    # argument "soluteModel" is missing, with no default
  )

})

