#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("verticalCmToMeters() works", {

  expect_error(
    kwb.demeau:::verticalCmToMeters()
    # argument "cm" is missing, with no default
  )

})

