#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("selectModelled() works", {

  expect_error(
    kwb.demeau:::selectModelled()
    # argument "modDf" is missing, with no default
  )

})

