#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("mainLabel() works", {

  expect_error(
    kwb.demeau:::mainLabel()
    # argument "model" is missing, with no default
  )

})

