#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("downloadMeteoData() works", {

  expect_error(
    kwb.demeau:::downloadMeteoData()
    # do not know how to convert 'meteoData$CET' to class “Date”
  )

})

