#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("modelConfiguration() works", {

  expect_error(
    kwb.demeau:::modelConfiguration()
    # argument "modelStructure" is missing, with no default
  )

})

