#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("addHorizontalDistances() works", {

  expect_error(
    kwb.demeau:::addHorizontalDistances()
    # argument "gisData" is missing, with no default
  )

})

