#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convertToListAndAddMoniColumns() works", {

  expect_error(
    kwb.demeau:::convertToListAndAddMoniColumns()
    # argument "df" is missing, with no default
  )

})

