#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("runSoluteModel() works", {

  expect_error(
    kwb.demeau:::runSoluteModel()
    # argument "preparedSoluteModel" is missing, with no default
  )

})

