#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("modelFitness() works", {

  expect_error(
    kwb.demeau:::modelFitness()
    # argument "modelledMeasured" is missing, with no default
  )

})

