#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("compareModelledMeasured() works", {

  expect_error(
    kwb.demeau:::compareModelledMeasured()
    # argument "moniDat" is missing, with no default
  )

})

