#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("defineHeadBoundary() works", {

  expect_error(
    kwb.demeau:::defineHeadBoundary()
    # argument "head" is missing, with no default
  )

})

