#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("runHeatModel() works", {

  expect_error(
    kwb.demeau:::runHeatModel()
    # argument "preparedHeatModel" is missing, with no default
  )

})

