#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convHeadBoundary() works", {

  expect_error(
    kwb.demeau:::convHeadBoundary()
    # argument "hydraulicGradient" is missing, with no default
  )

})

