#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("importShapefile() works", {

  expect_error(
    kwb.demeau:::importShapefile()
    # argument "shp.path" is missing, with no default
  )

})

