#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dominantTravelTimes() works", {

  expect_error(
    kwb.demeau:::dominantTravelTimes()
    # argument "concModelled" is missing, with no default
  )

})

