#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dominantTravelTimesAgg() works", {

  expect_error(
    kwb.demeau:::dominantTravelTimesAgg()
    # argument "domTimes" is missing, with no default
  )

})

