#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("fitnessAdaptedModelConfiguration() works", {

  expect_error(
    kwb.demeau:::fitnessAdaptedModelConfiguration()
    # argument "parameterValue" is missing, with no default
  )

})

