#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("genuchtenModel() works", {

  expect_error(
    kwb.demeau:::genuchtenModel()
    # argument "pressureHead" is missing, with no default
  )

})

