#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("removeFileExtension() works", {

  expect_error(
    kwb.demeau:::removeFileExtension()
    # argument "x" is missing, with no default
  )

})

