#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("renameValues() works", {

  expect_error(
    kwb.demeau:::renameValues()
    # argument "newVal" is missing, with no default
  )

})

