#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getFeatures() works", {

  expect_error(
    kwb.demeau:::getFeatures()
    # argument "gisData" is missing, with no default
  )

})

