#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("setFeatureIDs() works", {

  expect_error(
    kwb.demeau:::setFeatureIDs()
    # argument "x" is missing, with no default
  )

})

