#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convModelCoordinatesToNodes() works", {

  expect_error(
    kwb.demeau:::convModelCoordinatesToNodes()
    # argument "modelCoords" is missing, with no default
  )

})

