#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("setSoilZero() works", {

  expect_error(
    kwb.demeau:::setSoilZero()
    # argument "nodes" is missing, with no default
  )

})

