#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("importShapefiles() works", {

  expect_error(
    kwb.demeau:::importShapefiles()
    # no item called "package:shapefiles" on the search list
  )

})

